[canyon_sql]

[[canyon_sql.datasources]]
name = 'postgres'

[canyon_sql.datasources.auth]
postgresql = { basic = { username = 'zdc', password = 'ggprueba'}}

[canyon_sql.datasources.properties]
host = '192.168.1.250'
port = 5432
db_name = 'triforce'
