[debug]
address = "192.168.1.133"
log = "debug"
port = 8000

[development]
address = "0.0.0.0"
log = "debug"
port = 8000

# ROCKET_PROFILE=development cargo run

[release]
address = "0.0.0.0"
log = "critical"
port = 2727
